### ISSUE TITLE
Not working with 1.9

### ISSUE THREAD

**Issue by leNicDev** [traitor/Minecraft-Server-Mod#294]
Basically not working with MC 1.9. Looks like a strange bug.

EDIT:
I'll make some PRs

**Comment by hmksq** [comment]
Don't think about it, it is impossible to update.
If you want to help the community, here is a good project: https://github.com/SpongePowered/SpongeAPI

**Comment by chrisinajar** [comment]
This project is long dead and not intended to work anymore
